export const RESPONSIVE_COLUMN_CONFIG: {
  MIN_COLUMN_WIDTH: number
  DEFAULT_MIN_WIDTH: number
  DEFAULT_COLUMN_WIDTH: number
} = {
  MIN_COLUMN_WIDTH: 100,
  DEFAULT_MIN_WIDTH: 100,
  DEFAULT_COLUMN_WIDTH: 150,
};
